# Personal information shortcuts
matches:
  - trigger: ";me"
    replace: "Anthuan Vásquez"

  - trigger: ";me-mail"
    replace: "your@email.com"

  - trigger: ";me-site"
    replace: "https://anthuanvasquez.net"

  - trigger: ";me-gh"
    replace: "https://github.com/anthuanvasquez"

  - trigger: ";me-link"
    replace: "https://www.linkedin.com/in/anthuanvasquez"

  - trigger: ":today"
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":now"
    replace: "{{time}}"
    vars:
      - name: time
        type: date
        params:
          format: "%H:%M"
